export const GOWOORI_MCP_PROMPT_PACKS: Record<string, string> = {
  '00-shared-xcon-contract.md': [
    '# Shared XCON Generation Contract',
    '',
    'Use this contract with every XCON Viewer generation prompt.',
    '',
    '## Format Priority',
    'Prefer XCON/SKETCH, then XCON/JSON, then XML, then TAGLESS. For Markdown documents, visible syntax should be Markdown, XCON Chain SUGAR, XCON/SKETCH, then XCON Workflow.',
    '',
    '## XCON/SKETCH Hard Rules',
    '- Every renderable `xcon-sketch` fence must start with `screen`.',
    '- Do not put partial component snippets in an `xcon-sketch` fence.',
    '- Root screen must always include width and height.',
    '- All visual components must have stable dimensions using `at x y width height`.',
    '- Nested components use parent-local coordinates.',
    '- Do not add the parent panel screen x/y offset to child coordinates.',
    '- If text or controls visually belong on a panel, banner, card, or hero, nest them under that container by indentation. Do not rely on sibling overlap.',
    '- Use nested border and font blocks. Do not use CSS-like shorthand properties such as top-level radius, borderColor, fontSize, fontWeight, or lineHeight.',
    '- Keep JSON property values on one physical line after the property name for chartData, snapshot, markers, nodes, links, slides, and similar structured values.',
    '- Use public-safe components only: panel, label, button, textField, image, shape, banner, list, spanGrid, chart, networkDiagram, and map.',
    '- Do not generate removed or unsafe components: webView, frame, import, fileUpload, filePicker, imagePicker, signaturePad, or custom components.',
    '',
    '## List Contract',
    'Lists must include backgroundColor, direction/orientation, itemSize, separator with matching background color, dataTemplate.template.tabledata, and templates.cell with a named child layout such as card, row, or item.',
    '',
    '## SpanGrid Contract',
    'Use `spanGrid` when the output is table-like or spreadsheet-like. It should be read-only unless editing is explicitly requested.',
    'Prefer `snapshot` JSON for generated spanGrid content because it preserves rows, columns, row heights, borders, merges, and fixed panes reliably.',
    '',
    '## Markdown + Chain + Sketch Contract',
    'Use `xcon-chain-fixture` for source data and `xcon-chain as alias` fences for display-ready values. `$alias` values used in Markdown or SKETCH must be declared before use.',
    '',
    '## Workflow Contract',
    'Use `xcon-workflow` for action-flow documents. Workflows may use actions such as `note`, `callApi`, `workqueue`, and `scheduler`.',
    '',
    '## Final Self-Check',
    'Every xcon-sketch fence starts with screen, root screen has explicit dimensions, nested children fit their parent, lists have a named cell layout, unsupported components are absent, Chain aliases are declared before use, and the output is complete.',
  ].join('\n'),
  '01-sketch-ui-generation.md': [
    '# Prompt: Generate a Complete XCON/SKETCH UI',
    '',
    'Create a polished, complete, renderable XCON/SKETCH screen.',
    'Return a short Markdown heading and one complete ```xcon-sketch fence.',
    'The xcon-sketch fence must start with screen.',
    'Use concrete dimensions, stable layout, actual public image URLs when media is needed, icon names for icon-only buttons, spanGrid for tables, chart for metrics, networkDiagram for relationships, and map only for useful static location previews.',
    'For headers, cards, heroes, and colored panels, put title/subtitle/actions inside the parent panel so contrast and layout are deterministic.',
    'When generating lists, include backgroundColor, itemSize, separator with matching color, dataTemplate, and templates.cell with a named layout object.',
    'Self-review: every component fits, text does not overlap, lists are valid, repeated items look polished, and the result looks like production UI rather than a wireframe.',
  ].join('\n'),
  '02-markdown-xcon-document.md': [
    '# Prompt: Generate a Markdown + XCON/SKETCH Document',
    '',
    'Use Markdown for prose, headings, bullet lists, and explanatory text.',
    'Use XCON/SKETCH for visual cards, dashboards, grids, maps, diagrams, and structured document blocks.',
    'Every ```xcon-sketch fence must start with screen.',
    'Do not place partial snippets in xcon-sketch fences.',
    'Prefer SKETCH and SUGAR syntax over JSON.',
    'Use `spanGrid` for tables that should look like real tables.',
    'Use `chart` for metric visualization.',
    'Use `networkDiagram` for relationship or dependency visualization.',
    'Keep each visual block self-contained and renderable.',
  ].join('\n'),
  '03-xcon-chain-generation.md': [
    '# Prompt: Generate XCON Chain SUGAR',
    '',
    'Use `xcon-chain-fixture` for inline JSON fixture data and `xcon-chain as alias` for reusable display values.',
    'Prefer SUGAR pipelines such as `= record.metrics.revenue | format "$#,###"`.',
    'Do not use undeclared `$alias` values in Markdown or SKETCH.',
    'Use Chain to prepare values for SKETCH; do not put business logic directly inside visual components when an alias would be clearer.',
  ].join('\n'),
  '04-xcon-workflow-generation.md': [
    '# Prompt: Generate XCON Workflow',
    '',
    'Create one complete ```xcon-workflow fence with a clear workflow name and explicit step ids.',
    'Use `after` dependencies to make execution order clear.',
    'Use `note` for human-readable stages, `callApi` for remote or simulated service calls, `workqueue` for parallel item processing, and `scheduler` for repeated or delayed actions.',
    'Keep scheduler bounded with `iterations` when used in a local demo.',
    'Include `concurrency` on work queues. Do not invent action types.',
  ].join('\n'),
  '05-family-data-binding-template.md': [
    '# Prompt: Generate XCON Family Data Binding Template',
    '',
    'Create one coherent packet with Markdown, xcon-chain-fixture, xcon-chain aliases, xcon-sketch, and optional xcon-workflow.',
    'Treat fixture data as the source of truth. Chain prepares display-ready aliases. SKETCH renders aliases. Workflow changes fixture or operational state only when requested.',
  ].join('\n'),
  '06-monitoring-dashboard-workflow.md': [
    '# Prompt: Generate Monitoring Dashboard Workflow',
    '',
    'Use when the artifact should show a live or simulated operational monitor.',
    'Combine fixture state, Chain aliases, dashboard SKETCH, and Workflow steps that update queue/scheduler/progress state.',
    'The dashboard should make runtime state visible: progress, queue depth, current action, warnings, and final status.',
  ].join('\n'),
  '07-template-lab-business-document.md': [
    '# Prompt: Generate Template Lab Business Document',
    '',
    'Create business-ready Markdown documents such as invoices, quotes, briefs, bulletins, and checklists.',
    'Use Markdown for readable prose and XCON/SKETCH for tables, summary cards, charts, and printable visual blocks.',
    'Prefer data-bound fixture + Chain aliases when values may be reused or exported.',
  ].join('\n'),
  '08-review-and-repair.md': [
    '# Prompt: Review and Repair XCON Artifacts',
    '',
    'Review the artifact and repair it so it follows the shared XCON generation contract.',
    'Preserve the original intent, content, and visual hierarchy.',
    'Do not introduce unsupported components.',
    'Fix invalid list templates, invalid scroll values, missing screen dimensions, unknown action fields, broken Chain aliases, missing fixtures, and Workflow dependency order.',
    'If a broken artifact conflicts with the original user request, the original user request wins.',
  ].join('\n'),
  '09-chat-artifact-simulation.md': [
    '# Prompt: Generate a Chat Artifact Simulation',
    '',
    'Answer the user naturally in chat while also producing a live XCON/SKETCH artifact.',
    'Use Markdown for readable explanation and XCON/SKETCH when a visual card, dashboard, schedule, table, map, or workflow view communicates better than text alone.',
    'Do not mention that you are using XCON unless helpful.',
    'The chat answer should read naturally.',
    'Include one complete `xcon-sketch` fence for the visual artifact.',
    'The xcon-sketch fence must start with `screen`.',
    'The visual artifact should feel like a finished card or mini-dashboard.',
    'Use Chain or Workflow fences only if the answer needs live data binding or process visualization.',
    'Do not expose implementation logs in the chat answer.',
  ].join('\n'),
  '10-showcase-component-catalog.md': [
    '# Showcase Component Catalog',
    '',
    'Use richer XCON component composition when it helps: polished cards, hero banners, lists, charts, span grids, maps, network diagrams, badges, progress bars, tabs, selects, switches, sliders, ratings, and QR codes.',
    'Keep examples production-like and domain-specific rather than generic placeholder panels.',
  ].join('\n'),
  '11-auto-layout-layer-recipes.md': [
    '# Auto Layout And Layer Recipes',
    '',
    'Use stable coordinate layout unless the task benefits from auto layout.',
    'Layered hero/card designs must keep overlay text readable with explicit colors and bounded text regions.',
    'Overlay text must be nested inside the hero/card panel. Do not create a colored panel and then place root-level labels on top of it.',
    'Nested coordinates are parent-local. Do not double-add offsets.',
  ].join('\n'),
  '12-rich-list-xlist-recipes.md': [
    '# Rich List And XList Recipes',
    '',
    'Use list for feeds, rails, alerts, cards, and row collections.',
    'Every rendered list needs dataTemplate.template.tabledata and templates.cell with a named layout object.',
    'For item spacing, set separator.color to the list background color.',
  ].join('\n'),
  '13-dashboard-chart-map-network-recipes.md': [
    '# Dashboard, Chart, Map, And Network Recipes',
    '',
    'Use these recipes for analytical, operational, monitoring, and command-center artifacts.',
    'Prefer header, KPI cards, main visualization, and supporting queue/alert/detail sections.',
    'Use `spanGrid` for table-like data and `list` for alerts or cards.',
    '',
    'Known chart types from the XCON family examples include:',
    '- `chartType "bar"` for category comparison.',
    '- `chartType "line"` for time series.',
    '- `chartType "pie"` or `chartType "doughnut"` for composition.',
    '- `chartType "radar"` for capability or quality profiles.',
    '- `chartType "polarArea"` for radial category strength.',
    '- `chartType "scatter"` for correlation.',
    '- `chartType "bubble"` for risk, volume, and impact maps.',
    '',
    'Use `map` for location-aware operations with latitude, longitude, zoom, and markers.',
    'Use `networkDiagram` for relationships, dependencies, topology, or incident blast radius with nodes and links.',
  ].join('\n'),
  '14-family-binding-workflow-recipes.md': [
    '# Family Binding And Workflow Recipes',
    '',
    'Use this recipe when a document should stay data-bound across Markdown, Chain, SKETCH, and Workflow.',
    'Recommended order: Markdown title, xcon-chain-fixture, xcon-chain as aliases, xcon-sketch, optional xcon-workflow.',
    'Useful aliases include titleText, statusText, ownerText, updatedAtText, progressText, chartData, gridData, mapMarkers, networkNodes, and networkLinks.',
    'Workflow updates fixture data only. The SKETCH should not contain business logic that belongs in Chain or Workflow.',
  ].join('\n'),
  '15-domain-blueprints.md': [
    '# Domain Blueprints',
    '',
    'Choose domain-specific visual patterns instead of generic layouts.',
    'Weather: use forecast cards, charts, maps, and grids only when the active request is explicitly weather-related.',
    'Business reports: headline metrics, chart, table/spanGrid, risks, and next actions.',
    'Operations/workflow: status, queue, scheduler, timeline, alerts, and final outcome.',
    'Identity/help: compact Gowoori introduction card with clear capabilities and no stale domain content.',
  ].join('\n'),
};

export function createGowooriPromptPackSection(promptPacks: string[]): string[] {
  const uniquePacks = Array.from(new Set(promptPacks));
  const lines: string[] = [
    '',
    'MCP prompt pack excerpts:',
    'The following blocks are assembled from tools/xenesis-desk/mcp/prompts and are binding generation rules for this request.',
  ];

  for (const packName of uniquePacks) {
    const content = GOWOORI_MCP_PROMPT_PACKS[packName];
    if (!content) {
      lines.push(
        '',
        `## MCP prompt pack: ${packName}`,
        'Prompt pack is not bundled in the renderer. Follow the route goal and shared contract.',
      );
      continue;
    }
    lines.push('', `## MCP prompt pack: ${packName}`, content);
  }

  return lines;
}
