export function renderDashboardHtml() {
  return [
    "<!doctype html>",
    "<html lang=\"en\">",
    "<head>",
    "<meta charset=\"utf-8\">",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
    "<title>Xenesis Dashboard</title>",
    "<style>",
    ":root{color-scheme:light dark;font-family:Inter,Segoe UI,Arial,sans-serif;background:#f6f7f9;color:#1f2937}",
    "body{margin:0;background:#f6f7f9;color:#1f2937}",
    "header{border-bottom:1px solid #d8dee8;background:#ffffff;padding:16px 24px;display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}",
    "main{max-width:1180px;margin:0 auto;padding:18px 24px 32px}",
    "h1{font-size:22px;line-height:1.2;margin:0}",
    "h2{font-size:15px;line-height:1.3;margin:0 0 10px}",
    ".grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px;align-items:start}",
    ".panel{border:1px solid #d8dee8;background:#ffffff;border-radius:6px;padding:14px;margin-bottom:16px}",
    ".toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}",
    "textarea,input,select{box-sizing:border-box;width:100%;border:1px solid #bac4d1;border-radius:4px;background:#ffffff;color:#1f2937;padding:9px;font:inherit}",
    "textarea{min-height:108px;resize:vertical}",
    "button{border:1px solid #9aa6b6;border-radius:4px;background:#f3f5f8;color:#111827;padding:8px 10px;font:inherit;cursor:pointer}",
    "a{color:#1f6feb;text-decoration:none}",
    "button.primary{background:#1f6feb;border-color:#1f6feb;color:#ffffff}",
    "button:disabled{opacity:.55;cursor:not-allowed}",
    ".list{display:grid;gap:8px}",
    ".row{display:grid;grid-template-columns:110px 1fr auto;gap:10px;align-items:center;border-top:1px solid #edf0f4;padding-top:8px}",
    ".muted{color:#5f6b7a;font-size:12px}",
    "pre{white-space:pre-wrap;word-break:break-word;background:#111827;color:#e5e7eb;border-radius:6px;padding:12px;min-height:130px;max-height:360px;overflow:auto}",
    "@media(max-width:860px){.grid{grid-template-columns:1fr}.row{grid-template-columns:1fr}}",
    "</style>",
    "</head>",
    "<body>",
    "<header><div><h1>Xenesis Dashboard</h1><div id=\"status\" class=\"muted\">gateway</div></div><a id=\"openapi-link\" href=\"/openapi.json\">OpenAPI</a></header>",
    "<main>",
    "<div class=\"grid\">",
    "<section>",
    "<div class=\"panel\">",
    "<h2>Run</h2>",
    "<form id=\"prompt-form\">",
    "<textarea id=\"prompt-input\" name=\"prompt\" placeholder=\"Enter a prompt\"></textarea>",
  "<div class=\"toolbar\"><label class=\"muted\">Workflow<select id=\"workflow-select\" name=\"workflow\"><option value=\"default\">default</option></select></label></div>",
    "<div class=\"toolbar\"><button class=\"primary\" type=\"submit\">Stream Prompt</button><button type=\"button\" id=\"cancel-run\">Cancel Active</button><button type=\"button\" id=\"clear-output\">Clear</button></div>",
    "</form>",
    "</div>",
    "<div class=\"panel\">",
    "<h2>Checks</h2>",
    "<div class=\"toolbar\">",
    "<button id=\"run-smoke\" type=\"button\">Smoke</button>",
    "<button id=\"run-scenario\" type=\"button\">Scenario</button>",
    "<button id=\"run-connect\" type=\"button\">Connect</button>",
    "<label class=\"muted\"><input id=\"connect-probe\" type=\"checkbox\" style=\"width:auto\"> provider probe</label>",
    "</div>",
    "</div>",
    "<div class=\"panel\"><h2>Output</h2><pre id=\"output\"></pre></div>",
    "</section>",
    "<aside>",
    "<div class=\"panel\"><h2>Provider / MCP</h2><div id=\"connect-summary\" class=\"muted\">loading</div></div>",
    "<div class=\"panel\"><h2>Profile</h2><div class=\"toolbar\"><select id=\"profile-select\"></select><button id=\"profile-clear\" type=\"button\">Clear</button></div><div id=\"profile-summary\" class=\"muted\">loading</div></div>",
    "<div class=\"panel\"><h2>Active Runs</h2><div id=\"runs-list\" class=\"list\"></div></div>",
    "<div class=\"panel\"><h2>Reports</h2><div class=\"toolbar\"><select id=\"report-kind-filter\"><option value=\"\">All kinds</option><option value=\"smoke\">Smoke</option><option value=\"scenario\">Scenario</option><option value=\"connect\">Connect</option><option value=\"provider-live\">Provider live</option></select><select id=\"report-status-filter\"><option value=\"\">All results</option><option value=\"passed\">Passed</option><option value=\"failed\">Failed</option></select></div><div id=\"reports-list\" class=\"list\"></div></div>",
    "<div class=\"panel\"><h2>Tasks</h2><div class=\"toolbar\"><select id=\"task-status-filter\"><option value=\"\">All statuses</option><option value=\"queued\">Queued</option><option value=\"running\">Running</option><option value=\"completed\">Completed</option><option value=\"failed\">Failed</option><option value=\"cancelled\">Cancelled</option><option value=\"blocked\">Blocked</option></select><input id=\"task-handoff-filter\" placeholder=\"handoff / label\" /></div><div id=\"tasks-list\" class=\"list\"></div></div>",
    "<div class=\"panel\"><h2>Sessions</h2><div id=\"sessions-list\" class=\"list\"></div></div>",
    "<div class=\"panel\"><h2>Trace Diagnostics</h2><div class=\"toolbar\"><select id=\"trace-filter\"><option value=\"all\">All</option><option value=\"failed\">Failed</option><option value=\"warning\">Warning</option><option value=\"ok\">OK</option></select></div><div id=\"trace-summary-list\" class=\"list\"><span class=\"muted\">loading</span></div></div>",
    "<div class=\"panel\"><h2>Trace</h2><div id=\"trace-detail\" class=\"list\"><span class=\"muted\">select a trace</span></div></div>",
    "<div class=\"panel\"><h2>Failure Patterns</h2><div class=\"muted\">Frequent tool failures, repair stops, and handoff bottlenecks</div><div id=\"diagnostic-insights-list\" class=\"list\"><span class=\"muted\">loading</span></div></div>",
    "<div class=\"panel\"><h2>Adaptive Policy</h2><div class=\"muted\">Next-run guardrails derived from failure patterns</div><div id=\"adaptive-policy-list\" class=\"list\"><span class=\"muted\">loading</span></div></div>",
    "<div class=\"panel\"><h2>Observability</h2><div class=\"muted\">Task lifecycle and gateway events</div><div class=\"toolbar\"><select id=\"observability-task-status-filter\"><option value=\"\">All task events</option><option value=\"queued\">Queued</option><option value=\"running\">Running</option><option value=\"completed\">Completed</option><option value=\"failed\">Failed</option><option value=\"cancelled\">Cancelled</option><option value=\"blocked\">Blocked</option></select><input id=\"observability-handoff-filter\" placeholder=\"handoff / label\" /><button id=\"export-observability\" type=\"button\">Export</button><button id=\"clear-observability\" type=\"button\">Clear</button></div><div id=\"observability-list\" class=\"list\"></div></div>",
    "<div class=\"panel\"><h2>Context</h2><div id=\"context-summary\" class=\"muted\">loading</div></div>",
    "<div class=\"panel\"><h2>Artifacts</h2><div id=\"artifacts-list\" class=\"list\"></div></div>",
    "</aside>",
    "</div>",
    "</main>",
    "<script>",
    "const output=document.getElementById('output');",
    "const queryToken=new URLSearchParams(location.search).get('token')||'';",
    "let activeRunId='';",
    "let traceSummaries=[];",
    "document.getElementById('openapi-link').href=queryToken?`/openapi.json?token=${encodeURIComponent(queryToken)}`:'/openapi.json';",
    "const authHeaders=()=>queryToken?{authorization:`Bearer ${queryToken}`}:{ };",
    "const write=(value)=>{output.textContent=typeof value==='string'?value:JSON.stringify(value,null,2)};",
    "const append=(value)=>{output.textContent+=`${value}\\n`;output.scrollTop=output.scrollHeight;};",
    "async function json(url,options={}){const headers={...authHeaders(),...(options.headers||{})};const res=await fetch(url,{...options,headers});const body=await res.json();if(!res.ok)throw new Error(body.error||res.statusText);return body;}",
    "function formValue(id){const node=document.getElementById(id);return node&&'value'in node?node.value.trim():'';}",
    "function queryString(values){const params=new URLSearchParams();for(const [key,value] of Object.entries(values)){if(value!==undefined&&value!==null&&String(value).trim())params.set(key,String(value).trim());}return params.toString();}",
    "function traceButton(traceId){if(!traceId)return '';const encoded=encodeURIComponent(traceId);return `<button type=\"button\" onclick=\"showTrace(decodeURIComponent('${encoded}'))\">${traceId}</button>`;}",
    "function traceSummaryRow(trace){const d=trace.diagnostics||{};const counts=`sessions ${trace.sessionCount} / reports ${trace.runReportCount} / events ${trace.observabilityEventCount}`;const detail=`retries ${d.retryCount??0} / failed tools ${d.failedToolCallCount??0} / permission ${d.permissionIssueCount??0}`;return `<div class=\"row\"><strong>${trace.status}</strong><span>${traceButton(trace.traceId)}<br><span class=\"muted\">${counts}<br>${detail}</span></span><span class=\"muted\">${trace.updatedAt||''}</span></div>`;}",
    "function renderTraceSummaries(){const filter=document.getElementById('trace-filter').value;const visible=traceSummaries.filter(trace=>filter==='all'||trace.status===filter);document.getElementById('trace-summary-list').innerHTML=visible.map(traceSummaryRow).join('')||'<span class=\"muted\">none</span>';}",
    "function traceDetail(trace){const d=trace.diagnostics||{};const encoded=encodeURIComponent(trace.traceId);const actions=`<div class=\"toolbar\"><button type=\"button\" onclick=\"showTraceCompact(decodeURIComponent('${encoded}'))\">Compact</button><button type=\"button\" onclick=\"showTraceBundle(decodeURIComponent('${encoded}'))\">Bundle</button></div>`;const verification=d.verification?` / verification ${d.verification.status} (${d.verification.failedCommands.length} failed)`:'';const failedTools=(d.failedToolCalls||[]).map(tool=>`<div class=\"row\"><strong>tool failed</strong><span>${tool.name}<br><span class=\"muted\">${tool.content}</span></span><span></span></div>`).join('');const workflowSteps=workflowStepRows(trace.workflowSteps||[]);return `<div class=\"row\"><strong>trace</strong><span>${trace.traceId}<br><span class=\"muted\">active ${trace.activeRuns.length} / sessions ${trace.sessions.length} / reports ${trace.runReports.length} / events ${trace.observability.summary.total}</span></span><span>${actions}</span></div><div class=\"row\"><strong>diagnostics</strong><span>${d.status||'unknown'}<br><span class=\"muted\">retries ${d.retryCount??0} / fallbacks ${d.fallbackCount??0} / failed tools ${d.failedToolCallCount??0} / permission ${d.permissionIssueCount??0}${verification}</span></span><span></span></div>`+workflowSteps+failedTools+trace.sessions.map(session=>`<div class=\"row\"><strong>${session.status}</strong><span>${session.id}<br><span class=\"muted\">${session.phase||''}</span></span><span></span></div>`).join('')+trace.runReports.map(report=>`<div class=\"row\"><strong>report</strong><span>${report.sessionId}<br><span class=\"muted\">${report.status} / ${report.eventCount} events</span></span><span></span></div>`).join('');}",
    "function reportRow(report){const kind=report.kind,id=report.id;return `<div class=\"row\"><strong>${kind}</strong><span><button onclick=\"showReport('${kind}','${id}')\">${id}</button><br><span class=\"muted\">${report.passed}/${report.total} passed</span></span><span>${report.exitCode}</span></div>`;}",
  "function workflowName(workflow){return workflow?.name||'default';}",
    "function workflowOption(workflow){return `<option value=\"${workflow.name}\">${workflow.name}</option>`;}",
    "function workflowStepRows(steps=[]){return steps.map(step=>{const label=[step.workflow?.name,step.step?.name].filter(Boolean).join(' / ');const detail=[step.sessionId,step.durationMs!==undefined?`${step.durationMs}ms`:'',step.error].filter(Boolean).join(' / ');return `<div class=\"row\"><strong>${step.status}</strong><span>${label}<br><span class=\"muted\">${detail}</span></span><span>${step.index}/${step.total}</span></div>`;}).join('');}",
    "function runRow(run){const detail=[workflowName(run.workflow),run.id,run.sessionId].filter(Boolean).join(' / ');return `<div class=\"row\"><strong>${run.status}</strong><span>${run.prompt}<br><span class=\"muted\">${detail}</span><br>${traceButton(run.traceId)}</span><span><button onclick=\"cancelActiveRun('${run.id}')\">Cancel</button></span></div>`+workflowStepRows(run.workflowSteps||[]);}",
    "function sessionRow(session){const detail=[session.phase,session.updatedAt].filter(Boolean).join(' / ');return `<div class=\"row\"><strong>${session.status||'session'}</strong><span>${session.id}<br><span class=\"muted\">${detail}</span><br>${traceButton(session.traceId)}</span><span></span></div>`;}",
    "function taskRow(task){const id=task.id;return `<div class=\"row\"><strong>${task.status}</strong><span>${task.prompt}<br><span class=\"muted\">${id}</span></span><span class=\"toolbar\"><button onclick=\"runTask('${id}')\">Run</button><button onclick=\"cancelTask('${id}')\">Cancel</button></span></div>`;}",
    "function artifactRow(artifact){return `<div class=\"row\"><strong>${artifact.kind}</strong><span>${artifact.title}<br><span class=\"muted\">${artifact.id}</span></span><span>${artifact.bytes}</span></div>`;}",
    "function observabilityRow(event){if(event.kind==='task'){const label=[event.phase,event.taskStatus].filter(Boolean).join(' / ')||'Task lifecycle';const taskLabel=[event.label,event.handoffTitle,event.taskId].filter(Boolean).join(' / ');const attempt=event.attempt?`attempt ${event.attempt}${event.maxAttempts?`/${event.maxAttempts}`:''}`:'';const detail=[taskLabel,attempt,event.blockedReason].filter(Boolean).join(' - ')||event.timestamp;const metric=event.taskStatus||event.phase||'';return `<div class=\"row\"><strong>task</strong><span>${label}<br><span class=\"muted\">${detail}</span><br>${traceButton(event.traceId)}</span><span>${metric}</span></div>`;}const label=[event.method,event.path].filter(Boolean).join(' ')||event.kind;const detail=[event.runId,event.taskId].filter(Boolean).join(' / ')||event.timestamp;const metric=event.status??event.durationMs??event.delayMs??'';return `<div class=\"row\"><strong>${event.kind}</strong><span>${label}<br><span class=\"muted\">${detail}</span><br>${traceButton(event.traceId)}</span><span>${metric}</span></div>`;}",
    "function diagnosticInsightRows(status){const patterns=status.diagnostics?.failurePatterns||{};const toolRows=(patterns.topFailedTools||[]).slice(0,4).map(tool=>`<div class=\"row\"><strong>tool</strong><span>${tool.name}<br><span class=\"muted\">${tool.failures}/${tool.calls} failures across ${tool.runCount} run(s)</span></span><span>${tool.latestSessionId||''}</span></div>`);const repairRows=(patterns.repairStopReasons||[]).slice(0,4).map(reason=>`<div class=\"row\"><strong>repair</strong><span>${reason.reason}<br><span class=\"muted\">${(reason.failedCommands||[]).join(', ')}</span></span><span>${reason.count}</span></div>`);const handoffRows=(patterns.handoffBottlenecks||[]).slice(0,4).map(handoff=>`<div class=\"row\"><strong>handoff</strong><span>${handoff.title||handoff.handoffId}<br><span class=\"muted\">queued ${handoff.queued} / running ${handoff.running} / blocked ${handoff.blocked}</span></span><span>${handoff.active}/${handoff.total}</span></div>`);return [...toolRows,...repairRows,...handoffRows].join('')||'<span class=\"muted\">none</span>';}",
    "function adaptivePolicyRows(status){const policy=status.diagnostics?.adaptivePolicy;if(!policy?.active)return '<span class=\"muted\">inactive</span>';const requiredRows=Object.entries(policy.requiredBefore||{}).slice(0,5).map(([tool,requirements])=>`<div class=\"row\"><strong>${tool}</strong><span>requires before use<br><span class=\"muted\">${(requirements||[]).join(', ')||'none'}</span></span><span>guard</span></div>`);const recovery=(policy.recoveryActions||[]).slice(0,4).join(', ');const priority=(policy.toolStrategy?.preferredTools||policy.priorityTools||[]).slice(0,6).join(', ');const context=(policy.contextStrategy?.injectionOrder||[]).slice(0,6).join(' -> ');const provider=[policy.providerStrategy?.retry,policy.providerStrategy?.fallback].filter(Boolean).join(' / ');const external=(policy.externalStrategy?.statusFields||[]).slice(0,5).join(', ');const strategyRows=[`<div class=\"row\"><strong>recovery</strong><span>${recovery||'none'}<br><span class=\"muted\">${(policy.longRunningStrategy?.stopConditions||[]).join(', ')}</span></span><span>${policy.longRunningStrategy?.mode||''}</span></div>`,`<div class=\"row\"><strong>tools</strong><span>${priority||'none'}<br><span class=\"muted\">caution ${(policy.toolStrategy?.cautionTools||policy.cautionTools||[]).join(', ')}</span></span><span>priority</span></div>`,`<div class=\"row\"><strong>context</strong><span>${context||'none'}<br><span class=\"muted\">${policy.contextStrategy?.memoryUse||''}</span></span><span>inject</span></div>`,`<div class=\"row\"><strong>provider</strong><span>${provider||'default'}<br><span class=\"muted\">${(policy.providerStrategy?.escalationSignals||[]).join(', ')}</span></span><span>route</span></div>`,`<div class=\"row\"><strong>external</strong><span>${external||'none'}<br><span class=\"muted\">${policy.externalStrategy?.channelGuidance||''}</span></span><span>status</span></div>`];return [...requiredRows,...strategyRows].join('')||'<span class=\"muted\">none</span>';}",
    "function profileLabel(profile){return [profile.name,profile.provider,profile.model].filter(Boolean).join(' - ');}",
    "async function refresh(){",
    "/* fetch('/profiles') fetch('/workflows') fetch('/reports') fetch('/tasks') fetch('/sessions/status') fetch('/traces') fetch('/runs') fetch('/observability/events?limit=8') */",
    "const reportQuery=queryString({kind:formValue('report-kind-filter'),status:formValue('report-status-filter'),limit:12});",
    "const taskFilter=formValue('task-handoff-filter');",
    "const taskQuery=queryString({status:formValue('task-status-filter'),handoffTitle:taskFilter,label:taskFilter,limit:12});",
    "const observabilityFilter=formValue('observability-handoff-filter');",
    "const observabilityQuery=queryString({kind:'task',taskStatus:formValue('observability-task-status-filter'),handoffTitle:observabilityFilter,label:observabilityFilter,limit:8});",
    "const [status,profiles,workflows,reports,runs,tasks,sessions,traces,context,artifacts,observability]=await Promise.all([json('/status'),json('/profiles'),json('/workflows'),json(`/reports?${reportQuery}`),json('/runs'),json(`/tasks?${taskQuery}`),json('/sessions/status'),json('/traces'),json('/context'),json('/artifacts'),json(`/observability/events?${observabilityQuery}`)]);",
    "document.getElementById('status').textContent=`active runs: ${status.activeRuns} - tasks: ${status.tasks.total} - reports: ${status.reports.total} - retries: ${status.observability.retry} - errors: ${status.observability.error} - task events: ${status.observability.task||0}`;",
    "const workflowSelect=document.getElementById('workflow-select');",
  "const selectedWorkflow=workflowSelect.value||'default';",
    "const workflowItems=workflows.workflows||[];",
  "workflowSelect.innerHTML=workflowItems.map(workflowOption).join('')||'<option value=\"default\">default</option>';",
  "workflowSelect.value=workflowItems.some(workflow=>workflow.name===selectedWorkflow)?selectedWorkflow:'default';",
    "const profileSelect=document.getElementById('profile-select');",
    "profileSelect.innerHTML='<option value=\"\">No active profile</option>'+profiles.profiles.map(profile=>`<option value=\"${profile.name}\">${profileLabel(profile)}</option>`).join('');",
    "profileSelect.value=profiles.active||'';",
    "document.getElementById('profile-summary').textContent=profiles.active?`active: ${profiles.active}`:'no active profile';",
    "document.getElementById('runs-list').innerHTML=runs.runs.map(runRow).join('')||'<span class=\"muted\">none</span>';",
    "document.getElementById('reports-list').innerHTML=reports.reports.map(reportRow).join('')||'<span class=\"muted\">none</span>';",
    "document.getElementById('tasks-list').innerHTML=tasks.tasks.map(taskRow).join('')||'<span class=\"muted\">none</span>';",
    "document.getElementById('sessions-list').innerHTML=sessions.sessions.map(sessionRow).join('')||'<span class=\"muted\">none</span>';",
    "traceSummaries=traces.traces||[];renderTraceSummaries();",
    "document.getElementById('diagnostic-insights-list').innerHTML=diagnosticInsightRows(status);",
    "document.getElementById('adaptive-policy-list').innerHTML=adaptivePolicyRows(status);",
    "document.getElementById('observability-list').innerHTML=observability.events.slice(-8).reverse().map(observabilityRow).join('')||'<span class=\"muted\">none</span>';",
    "document.getElementById('context-summary').textContent=context.fileCount?`${context.fileCount} files - ${context.totalSize} bytes - ${context.indexedAt}`:'no context index';",
    "document.getElementById('artifacts-list').innerHTML=artifacts.artifacts.map(artifactRow).join('')||'<span class=\"muted\">none</span>';",
    "const connect=reports.reports.find(r=>r.kind==='connect');",
    "document.getElementById('connect-summary').textContent=connect?`${connect.id}: ${connect.passed}/${connect.total} passed`:'no connect report';",
    "}",
    "async function showReport(kind,id){write(await json(`/reports/${kind}/${id}`));}",
    "async function showTrace(traceId){const trace=await json(`/traces/${encodeURIComponent(traceId)}`);document.getElementById('trace-detail').innerHTML=traceDetail(trace)||'<span class=\"muted\">none</span>';write(trace);}",
    "async function showTraceCompact(traceId){write(await json(`/traces/${encodeURIComponent(traceId)}/compact`));}",
    "async function showTraceBundle(traceId){write(await json(`/traces/${encodeURIComponent(traceId)}/bundle`));}",
    "async function streamPrompt(prompt){",
    "write('');",
  "const res=await fetch('/run/stream',{method:'POST',headers:{...authHeaders(),'content-type':'application/json'},body:JSON.stringify({prompt,workflow:document.getElementById('workflow-select').value||'default'})});",
    "if(!res.ok){write(await res.json());return;}",
    "const reader=res.body.getReader();const decoder=new TextDecoder();let buffer='';",
    "while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\\n\\n');buffer=chunks.pop()||'';for(const chunk of chunks){const event=chunk.match(/^event: (.+)$/m)?.[1]||'message';const data=chunk.split(/\\r?\\n/).filter(line=>line.startsWith('data: ')).map(line=>line.slice(6)).join('\\n');const parsed=data?JSON.parse(data):{};if(event==='gateway_run'){activeRunId=parsed.id;}if(event==='gateway_workflow_step'){append(`workflow step ${parsed.index}/${parsed.total}: ${parsed.step?.name||'step'}`);}else{append(`${event}: ${data}`);}}}",
    "await refresh();",
    "}",
    "document.getElementById('prompt-form').addEventListener('submit',async(event)=>{event.preventDefault();const prompt=document.getElementById('prompt-input').value.trim();if(!prompt)return;await streamPrompt(prompt);});",
    "document.getElementById('profile-select').addEventListener('change',async(event)=>{const name=event.target.value;if(!name){write(await json('/profiles/clear',{method:'POST'}));}else{write(await json('/profiles/use',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})}));}await refresh();});",
    "document.getElementById('profile-clear').addEventListener('click',async()=>{write(await json('/profiles/clear',{method:'POST'}));await refresh();});",
    "document.getElementById('run-smoke').addEventListener('click',async()=>{write(await json('/checks/smoke',{method:'POST'}));await refresh();});",
    "document.getElementById('run-scenario').addEventListener('click',async()=>{write(await json('/checks/scenario',{method:'POST'}));await refresh();});",
    "document.getElementById('run-connect').addEventListener('click',async()=>{write(await json('/checks/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({probe:document.getElementById('connect-probe').checked})}));await refresh();});",
    "async function runTask(id){write(await json(`/tasks/${id}/run`,{method:'POST'}));await refresh();}",
    "async function cancelTask(id){write(await json(`/tasks/${id}/cancel`,{method:'POST'}));await refresh();}",
    "async function cancelActiveRun(id=activeRunId){if(!id)return;write(await json(`/runs/${id}/cancel`,{method:'POST'}));await refresh();}",
    "async function exportObservability(){write(await json('/observability/events/export'));}",
    "async function clearObservability(){write(await json('/observability/events/clear',{method:'POST'}));await refresh();}",
    "document.getElementById('cancel-run').addEventListener('click',()=>cancelActiveRun());",
    "document.getElementById('export-observability').addEventListener('click',()=>exportObservability());",
    "document.getElementById('clear-observability').addEventListener('click',()=>clearObservability());",
    "document.getElementById('trace-filter').addEventListener('change',()=>renderTraceSummaries());",
    "['report-kind-filter','report-status-filter','task-status-filter','observability-task-status-filter'].forEach(id=>document.getElementById(id).addEventListener('change',()=>refresh().catch(error=>write(error.message))));",
    "['task-handoff-filter','observability-handoff-filter'].forEach(id=>document.getElementById(id).addEventListener('input',()=>refresh().catch(error=>write(error.message))));",
    "document.getElementById('clear-output').addEventListener('click',()=>write(''));",
    "refresh().catch(error=>write(error.message));",
    "</script>",
    "</body></html>"
  ].join("");
}
