export const APP_MENU_ICON_ALIASES: Record<string, string> = {
  action: '▶',
  'agent-sessions': 'AS',
  ai: '✧',
  audit: '✓',
  automation: '⚡',
  bot: '◉',
  browser: '◎',
  capability: '◈',
  channels: '◫',
  command: '⌘',
  'command-center': '⌘',
  database: '▤',
  desk: '▦',
  developer: '⌘',
  diagnostics: '◌',
  edit: '✎',
  'edit-safe': '✎',
  extension: '⊞',
  extensions: '⊞',
  file: '▤',
  gateway: '⇆',
  'git-branch': '⎇',
  gowoori: '◎',
  grid: '▦',
  help: 'ⓘ',
  hermes: '✦',
  horizontal: '↔',
  inbox: '▣',
  inspect: '◌',
  lab: '⚗',
  layout: '▧',
  library: '▤',
  log: '▤',
  markdown: '▤',
  meta: '▦',
  mcp: '⇆',
  'message-square': '□',
  mirror: '◫',
  monitor: '◉',
  network: '⌁',
  onboarding: '◈',
  performance: '▥',
  play: '▶',
  preview: '◉',
  process: '▥',
  query: '⌕',
  'query-od': '⌕',
  settings: '⚙',
  sqlite: '▤',
  stash: '▤',
  status: '●',
  sync: '⇆',
  task: '▶',
  terminal: '⌁',
  'terminal-inspector': '⌁',
  timeline: '◷',
  tools: '◈',
  tui: '▥',
  vault: '▤',
  vertical: '↕',
  'window-size': '□',
  workflow: '⇄',
  xamong: '⬡',
  'xamong-code': '⬡',
  xd: '◆',
  'xd-blaster': '◆',
  xenesis: '◇',
  'xenesis-agent': '◇',
  zap: '⚡',
  'app-control': '▣',
};

export function resolveAppMenuIcon(icon?: string | null, fallback = '▣'): string {
  const trimmed = icon?.trim();
  if (!trimmed) return fallback;

  return APP_MENU_ICON_ALIASES[trimmed.toLowerCase()] ?? trimmed;
}
