exports.activate = function activate(api) {
  api.registerCommand('sample.xcon-gallery.openSketch', function openSketch() {
    api.openMarkdown(
      'XCON Operations Dashboard',
      [
        '# XCON Operations Dashboard',
        '',
        'A production-style XCON/SKETCH dashboard opened as Markdown so the preview and editable source stay together.',
        '',
        '```xcon-sketch mode=both',
        'screen "Operations Signal Board" 1180x720 bg #07111f',
        '  header: panel at 28 24 1124 86',
        '    backgroundColor "#0f172a"',
        '    border',
        '      visible true',
        '      color "#1e3a5f"',
        '      radius 18',
        '    eyebrow: label "XCON/SKETCH SAMPLE" at 28 18 220 18',
        '      color "#38bdf8"',
        '      font',
        '        size 12',
        '        weight 800',
        '    title: label "Operations Signal Board" at 28 38 430 34',
        '      color "#f8fafc"',
        '      font',
        '        size 28',
        '        weight 900',
        '    subtitle: label "Rendered dashboard opened by sample.xcon-gallery" at 28 70 520 20',
        '      color "#94a3b8"',
        '      font',
        '        size 13',
        '        weight 600',
        '    liveBadge: label "LIVE CAPACITY" at 952 27 132 34',
        '      backgroundColor "#052e2b"',
        '      color "#bbf7d0"',
        '      align "center"',
        '      border',
        '        visible true',
        '        color "#22c55e"',
        '        radius 17',
        '      font',
        '        size 11',
        '        weight 800',
        '',
        '  metrics: panel at 28 130 1124 156',
        '    backgroundColor "#081827"',
        '    border',
        '      visible true',
        '      color "#1e3a5f"',
        '      radius 18',
        '    metric1: panel at 24 24 250 108',
        '      backgroundColor "#0b1f3a"',
        '      border',
        '        visible true',
        '        color "#1d4ed8"',
        '        radius 14',
        '      metric1Label: label "Live Capacity" at 24 20 150 20',
        '        color "#93c5fd"',
        '        font',
        '          size 13',
        '          weight 800',
        '      metric1Value: label "82%" at 24 46 120 42',
        '        color "#f8fafc"',
        '        font',
        '          size 36',
        '          weight 900',
        '    metric2: panel at 294 24 250 108',
        '      backgroundColor "#2a1f05"',
        '      border',
        '        visible true',
        '        color "#f59e0b"',
        '        radius 14',
        '      metric2Label: label "SLA Risk" at 24 20 150 20',
        '        color "#fcd34d"',
        '        font',
        '          size 13',
        '          weight 800',
        '      metric2Value: label "7" at 24 46 120 42',
        '        color "#fffbeb"',
        '        font',
        '          size 36',
        '          weight 900',
        '    metric3: panel at 564 24 250 108',
        '      backgroundColor "#2b0b16"',
        '      border',
        '        visible true',
        '        color "#fb7185"',
        '        radius 14',
        '      metric3Label: label "Incident Queue" at 24 20 160 20',
        '        color "#fda4af"',
        '        font',
        '          size 13',
        '          weight 800',
        '      metric3Value: label "14" at 24 46 120 42',
        '        color "#fff1f2"',
        '        font',
        '          size 36',
        '          weight 900',
        '    metric4: panel at 834 24 250 108',
        '      backgroundColor "#09251c"',
        '      border',
        '        visible true',
        '        color "#10b981"',
        '        radius 14',
        '      metric4Label: label "Automation Pass" at 24 20 170 20',
        '        color "#86efac"',
        '        font',
        '          size 13',
        '          weight 800',
        '      metric4Value: label "96%" at 24 46 130 42',
        '        color "#f0fdf4"',
        '        font',
        '          size 36',
        '          weight 900',
        '',
        '  work: panel at 28 306 690 382',
        '    backgroundColor "#0b1728"',
        '    border',
        '      visible true',
        '      color "#1e3a5f"',
        '      radius 18',
        '    workTitle: label "Incident Queue" at 28 28 220 24',
        '      color "#f8fafc"',
        '      font',
        '        size 19',
        '        weight 900',
        '    workSub: label "Grouped by blast radius and owner readiness" at 28 56 360 18',
        '      color "#94a3b8"',
        '      font',
        '        size 12',
        '        weight 600',
        '    row1: panel at 28 100 634 62',
        '      backgroundColor "#111f33"',
        '      border',
        '        visible true',
        '        color "#334155"',
        '        radius 12',
        '      row1A: label "P0" at 20 18 46 20',
        '        color "#fecaca"',
        '        font',
        '          size 15',
        '          weight 900',
        '      row1B: label "Payment callback lag above threshold" at 74 10 330 20',
        '        color "#f8fafc"',
        '        font',
        '          size 14',
        '          weight 800',
        '      row1C: label "Owner: API Platform" at 74 34 190 18',
        '        color "#94a3b8"',
        '        font',
        '          size 12',
        '          weight 600',
        '    row2: panel at 28 174 634 62',
        '      backgroundColor "#111f33"',
        '      border',
        '        visible true',
        '        color "#334155"',
        '        radius 12',
        '      row2A: label "P1" at 20 18 46 20',
        '        color "#fed7aa"',
        '        font',
        '          size 15',
        '          weight 900',
        '      row2B: label "Search indexing queue needs drain" at 74 10 330 20',
        '        color "#f8fafc"',
        '        font',
        '          size 14',
        '          weight 800',
        '      row2C: label "Owner: Data Tools" at 74 34 190 18',
        '        color "#94a3b8"',
        '        font',
        '          size 12',
        '          weight 600',
        '    row3: panel at 28 248 634 62',
        '      backgroundColor "#111f33"',
        '      border',
        '        visible true',
        '        color "#334155"',
        '        radius 12',
        '      row3A: label "P2" at 20 18 46 20',
        '        color "#bae6fd"',
        '        font',
        '          size 15',
        '          weight 900',
        '      row3B: label "Release note approval pending" at 74 10 330 20',
        '        color "#f8fafc"',
        '        font',
        '          size 14',
        '          weight 800',
        '      row3C: label "Owner: Documentation" at 74 34 190 18',
        '        color "#94a3b8"',
        '        font',
        '          size 12',
        '          weight 600',
        '',
        '  right: panel at 738 306 414 382',
        '    backgroundColor "#0b1728"',
        '    border',
        '      visible true',
        '      color "#1e3a5f"',
        '      radius 18',
        '    rightTitle: label "Response Plan" at 28 28 220 24',
        '      color "#f8fafc"',
        '      font',
        '        size 19',
        '        weight 900',
        '    step1n: label "1" at 28 78 34 34',
        '      backgroundColor "#2563eb"',
        '      color "#ffffff"',
        '      align "center"',
        '      border',
        '        visible false',
        '        radius 17',
        '      font',
        '        size 14',
        '        weight 900',
        '    step1t: label "Confirm owner and scope" at 76 80 240 20',
        '      color "#e0f2fe"',
        '      font',
        '        size 14',
        '        weight 800',
        '    step1s: label "Map alert to team channel and escalation rule." at 76 104 280 18',
        '      color "#94a3b8"',
        '      font',
        '        size 12',
        '        weight 600',
        '    step2n: label "2" at 28 156 34 34',
        '      backgroundColor "#0f766e"',
        '      color "#ffffff"',
        '      align "center"',
        '      border',
        '        visible false',
        '        radius 17',
        '      font',
        '        size 14',
        '        weight 900',
        '    step2t: label "Run automation smoke" at 76 158 240 20',
        '      color "#e0f2fe"',
        '      font',
        '        size 14',
        '        weight 800',
        '    step2s: label "Attach command result to the incident record." at 76 182 280 18',
        '      color "#94a3b8"',
        '      font',
        '        size 12',
        '        weight 600',
        '    step3n: label "3" at 28 234 34 34',
        '      backgroundColor "#7c3aed"',
        '      color "#ffffff"',
        '      align "center"',
        '      border',
        '        visible false',
        '        radius 17',
        '      font',
        '        size 14',
        '        weight 900',
        '    step3t: label "Publish recovery note" at 76 236 240 20',
        '      color "#e0f2fe"',
        '      font',
        '        size 14',
        '        weight 800',
        '    step3s: label "Use Markdown operations brief for the handoff." at 76 260 280 18',
        '      color "#94a3b8"',
        '      font',
        '        size 12',
        '        weight 600',
        '```',
      ].join('\n'),
    );
  });
};
