const publicRuntimeContractSnapshot = {
  version: 1,
  runtimeExports: [
    'AgentRunPipelineOptions',
    'AgentRunPipelineResult',
    'AgentRunEvent',
    'AgentMessage',
    'Tool',
    'ToolRegistry',
    'XenesisConfig',
    'runHeadlessPrompt',
    'runEmbeddedPrompt',
    'runAgentPipeline',
    'runAgentPrompt',
    'composeSystemPrompt',
    'resolveEffectiveSystemPromptBlocks',
    'fingerprintPromptBlocks',
    'systemPromptDynamicBoundary',
    'toSystemPromptSnapshot',
    'compareSystemPromptSnapshots',
    'repairToolResultPairing',
    'SYNTHETIC_TOOL_RESULT_PLACEHOLDER',
    'classifyProviderFailure',
  ],
  pipelineOptionKeys: [
    'cwd',
    'configPath',
    'env',
    'cli',
    'prompt',
    'mode',
    'savePlan',
    'fromPlan',
    'systemMessages',
    'historyMessages',
    'sessionId',
    'traceId',
    'ideContext',
    'abortSignal',
    'maxTokensBudget',
    'approvalHandler',
    'approvalHandlerFactory',
    'stream',
    'onEvent',
    'onMessages',
    'onSessionWriter',
    'onNotice',
    'workflowStep',
    'guard',
    'toolExecutionPolicy',
    'applyConfiguredWorkflow',
  ],
  pipelineResultKeys: [
    'exitCode',
    'sessionId',
    'traceId',
    'events',
    'doneContent',
    'turns',
    'usage',
    'runReport',
    'selfReview',
  ],
  sessionEventTypes: [
    'user_message',
    'assistant_message',
    'provider_retry',
    'provider_fallback',
    'context_recovery',
    'context_compact',
    'artifact',
    'workspace_change',
    'run_state',
    'workflow_step',
    'run_stage',
    'context_source',
    'tool_call',
    'tool_policy_snapshot',
    'tool_choice_audit',
    'tool_result_stored',
    'tool_result',
    'tool_policy_audit',
    'tool_event',
    'permission_audit',
    'permission_request',
    'done',
    'incomplete_run',
    'stopped',
    'verification_result',
    'repair_decision',
    'run_self_review',
    'error',
  ],
  configKeys: [
    'provider',
    'model',
    'xenesisHome',
    'baseURL',
    'apiKeyEnv',
    'providerRetries',
    'providerFallbacks',
    'providers',
    'context',
    'verification',
    'guard',
    'workflow',
    'workflows',
    'worker',
    'channels',
    'browser',
    'web',
    'maxTurns',
    'workspace',
    'approvalMode',
    'extensions',
    'permissions',
  ],
  toolCoreKeys: [
    'name',
    'description',
    'inputSchema',
    'openaiInputSchema',
    'isReadOnly',
    'isConcurrencySafe',
    'run',
    'cleanupSession',
  ],
} as const;

for (const value of Object.values(publicRuntimeContractSnapshot)) {
  if (Array.isArray(value)) {
    Object.freeze(value);
  }
}

export const publicRuntimeContract = Object.freeze(publicRuntimeContractSnapshot);

export type PublicRuntimeContract = typeof publicRuntimeContract;
export type PublicRuntimeEventType = PublicRuntimeContract['sessionEventTypes'][number];

export function getPublicRuntimeContract(): PublicRuntimeContract {
  return publicRuntimeContract;
}

export function isPublicRuntimeEventType(type: string): type is PublicRuntimeEventType {
  return (publicRuntimeContract.sessionEventTypes as readonly string[]).includes(type);
}
