exports.activate = function activate(api) {
  api.registerCommand('sample.markdown-tools.openGuide', function openGuide() {
    api.openMarkdown(
      'Release Readiness Brief',
      [
        '# Release Readiness Brief',
        '',
        'This operator-ready Markdown brief is created by the Markdown Operations Brief sample and opened through the standard Markdown pane.',
        '',
        '## Executive snapshot',
        '',
        '| Stream | Status | Owner | Next checkpoint |',
        '|---|---:|---|---|',
        '| Extension command surface | Ready | Platform | Menu smoke test |',
        '| Markdown rendering | Ready | Docs | Save/export check |',
        '| XCON preview handoff | Watch | Gowoori | Visual render check |',
        '',
        '## Decision Log',
        '',
        '- Use Markdown for operator-facing runbooks that need normal editor save behavior.',
        '- Embed XCON/SKETCH fences when a document should carry a live visual artifact beside text.',
        '- Keep generated documents deterministic so CLI agents and extensions can verify outputs.',
        '',
        '## Verification Checklist',
        '',
        '- [ ] Command appears in Tools and Command Palette.',
        '- [ ] Markdown tab opens with the expected title.',
        '- [ ] XCON fence remains editable and renderable.',
        '- [ ] Saving the document preserves tables, checklists, and fences.',
        '',
        '## Embedded XCON preview',
        '',
        '```xcon-sketch mode=both',
        'screen "Readiness Card" 720x360 bg #0f172a',
        '  board: panel at 24 24 672 312',
        '    backgroundColor "#0f172a"',
        '    border',
        '      visible true',
        '      color "#1e3a5f"',
        '      radius 18',
        '    title: label "Release Readiness" at 30 24 420 34',
        '      color "#f8fafc"',
        '      font',
        '        size 24',
        '        weight 800',
        '    summary: label "Markdown + XCON handoff is ready for operator review." at 30 64 500 24',
        '      color "#93c5fd"',
        '      font',
        '        size 14',
        '        weight 600',
        '    docs: panel at 30 116 176 90',
        '      backgroundColor "#052e2b"',
        '      border',
        '        visible true',
        '        color "#22c55e"',
        '        radius 12',
        '      docsLabel: label "Docs" at 20 16 100 20',
        '        color "#86efac"',
        '        font',
        '          size 13',
        '          weight 800',
        '      docsValue: label "Ready" at 20 44 120 28',
        '        color "#f0fdf4"',
        '        font',
        '          size 22',
        '          weight 900',
        '    preview: panel at 226 116 176 90',
        '      backgroundColor "#2a1f05"',
        '      border',
        '        visible true',
        '        color "#f59e0b"',
        '        radius 12',
        '      previewLabel: label "Preview" at 20 16 100 20',
        '        color "#fcd34d"',
        '        font',
        '          size 13',
        '          weight 800',
        '      previewValue: label "Watch" at 20 44 120 28',
        '        color "#fffbeb"',
        '        font',
        '          size 22',
        '          weight 900',
        '    next: panel at 422 116 176 90',
        '      backgroundColor "#0b1f3a"',
        '      border',
        '        visible true',
        '        color "#38bdf8"',
        '        radius 12',
        '      nextLabel: label "Next" at 20 16 100 20',
        '        color "#7dd3fc"',
        '        font',
        '          size 13',
        '          weight 800',
        '      nextValue: label "Smoke" at 20 44 120 28',
        '        color "#f0f9ff"',
        '        font',
        '          size 22',
        '          weight 900',
        '```',
      ].join('\n'),
    );
  });
};
