exports.activate = function activate(api) {
  api.registerCommand('sample.xenesis-mcp.openGuide', function openGuide() {
    api.openMarkdown(
      'MCP Operator Runbook',
      [
        '# MCP Operator Runbook',
        '',
        'This runbook shows how an MCP-capable CLI agent can discover Xenesis Desk, inspect the Capability Registry, and run CR control smoke tests without leaving the operator workflow.',
        '',
        '## Runtime contract',
        '',
        'When a local CLI environment is injected into a Desk terminal, the terminal receives these variables:',
        '',
        '| Variable | Purpose |',
        '|---|---|',
        '| `XENIS_MCP_SERVER_COMMAND` | Command used to launch the bundled MCP server. |',
        '| `XENIS_MCP_SERVER_PATH` | Absolute path to the MCP stdio server script. |',
        '| `XENIS_MCP_BRIDGE_URL` | Local bridge URL used by the server to reach Desk. |',
        '| `XENIS_MCP_CONFIG_FILE` | Generated config file path for supported clients. |',
        '| `XENIS_MCP_CONFIG_SNIPPET` | Copyable config snippet for manual setup. |',
        '',
        '## Capability Registry discovery',
        '',
        'Use read-only discovery before running controls:',
        '',
        '```text',
        '1. Run `xenis_desk_capabilities` to list registry groups.',
        '2. Run `xenis_desk_capability` for the exact path you plan to call.',
        '3. Prefer `xenis_desk_state` when you need current panes, files, terminals, and diagnostics.',
        '```',
        '',
        '## CR control smoke test',
        '',
        'The safest first write is a panel-open or generated Markdown action with explicit placement:',
        '',
        '```json',
        '{',
        '  "commandId": "sample.hello-world.openPanel",',
        '  "panelPlacement": "right"',
        '}',
        '```',
        '',
        'Run it through `xenis_run_extension_command`. The command should return an `openPanel` action and Desk should place the Extension Status Console on the right.',
        '',
        '## Extension command tools',
        '',
        '- `xenis_list_extension_commands` lists registered extension commands.',
        '- `xenis_run_extension_command` runs a command and dispatches its UI actions to Xenesis Desk.',
        '- `placement` controls generated files and Markdown tabs.',
        '- `panelPlacement` controls extension panels opened through `api.openPanel()`.',
        '',
        '## Guardrails',
        '',
        '- Read the Capability Registry entry before invoking a control path.',
        '- Use exact command IDs; do not guess extension IDs.',
        '- Treat generated documents and opened panels as Desk actions, not shell execution.',
        '- Keep secrets out of prompts, Markdown output, and extension sample files.',
        '',
        '## Minimal MCP config',
        '',
        '```json',
        '{',
        '  "mcpServers": {',
        '    "xenesis": {',
        '      "command": "node",',
        '      "args": ["%XENIS_MCP_SERVER_PATH%"]',
        '    }',
        '  }',
        '}',
        '```',
      ].join('\n'),
    );
  });
};
