export const SETTINGS_CATEGORIES = [
  {
    id: 'xenesis-agent',
    icon: 'XG',
    titleKey: 'settings.category.xenesisAgent',
    descriptionKey: 'settings.category.xenesisAgentDesc',
  },
  {
    id: 'run-model',
    icon: 'AI',
    titleKey: 'settings.category.runModel',
    descriptionKey: 'settings.category.runModelDesc',
  },
  {
    id: 'remote-terminals',
    icon: '⇄',
    titleKey: 'settings.category.remoteTerminals',
    descriptionKey: 'settings.category.remoteTerminalsDesc',
  },
  {
    id: 'remote-files',
    icon: '⇅',
    titleKey: 'settings.category.remoteFiles',
    descriptionKey: 'settings.category.remoteFilesDesc',
  },
  {
    id: 'automation',
    icon: '🤖',
    titleKey: 'settings.category.automation',
    descriptionKey: 'settings.category.automationDesc',
  },
  {
    id: 'external-apps',
    icon: 'APP',
    titleKey: 'settings.category.externalApps',
    descriptionKey: 'settings.category.externalAppsDesc',
  },
  {
    id: 'extensions',
    icon: '▦',
    titleKey: 'settings.category.extensions',
    descriptionKey: 'settings.category.extensionsDesc',
  },
  {
    id: 'workspace',
    icon: '▤',
    titleKey: 'settings.category.workspace',
    descriptionKey: 'settings.category.workspaceDesc',
  },
  {
    id: 'interface',
    icon: 'UI',
    titleKey: 'settings.category.interface',
    descriptionKey: 'settings.category.interfaceDesc',
  },
  {
    id: 'info',
    icon: 'ⓘ',
    titleKey: 'settings.category.info',
    descriptionKey: 'settings.category.infoDesc',
  },
  {
    id: 'general',
    icon: '◎',
    titleKey: 'settings.category.general',
    descriptionKey: 'settings.category.generalDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'language',
    icon: '文',
    titleKey: 'settings.category.language',
    descriptionKey: 'settings.category.languageDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'appearance',
    icon: '☼',
    titleKey: 'settings.category.appearance',
    descriptionKey: 'settings.category.appearanceDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'keyboard-shortcuts',
    icon: '⌘',
    titleKey: 'settings.category.keyboardShortcuts',
    descriptionKey: 'settings.category.keyboardShortcutsDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'window-sizer',
    icon: '▣',
    titleKey: 'settings.category.windowSizer',
    descriptionKey: 'settings.category.windowSizerDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'secret-vault',
    icon: '◇',
    titleKey: 'settings.category.secretVault',
    descriptionKey: 'settings.category.secretVaultDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'settings-backup',
    icon: '⇪',
    titleKey: 'settings.category.settingsBackup',
    descriptionKey: 'settings.category.settingsBackupDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'about',
    icon: 'ⓘ',
    titleKey: 'settings.category.about',
    descriptionKey: 'settings.category.aboutDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'media',
    icon: '▧',
    titleKey: 'settings.category.media',
    descriptionKey: 'settings.category.mediaDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'connectors',
    icon: '☷',
    titleKey: 'settings.category.connectors',
    descriptionKey: 'settings.category.connectorsDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'mcp',
    icon: '↗',
    titleKey: 'settings.category.mcp',
    descriptionKey: 'settings.category.mcpDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'notifications',
    icon: '♧',
    titleKey: 'settings.category.notifications',
    descriptionKey: 'settings.category.notificationsDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'pets',
    icon: '✦',
    titleKey: 'settings.category.pets',
    descriptionKey: 'settings.category.petsDesc',
    hiddenInSettingsPane: true,
  },
  {
    id: 'skills-design',
    icon: '▦',
    titleKey: 'settings.category.skillsDesign',
    descriptionKey: 'settings.category.skillsDesignDesc',
    hiddenInSettingsPane: true,
  },
];

export const VISIBLE_SETTINGS_CATEGORIES = SETTINGS_CATEGORIES.filter(
  (category) => category.hiddenInSettingsPane !== true,
);
